const Data = [
  {
    id: 1,
    imgURL:
      "https://images.pexels.com/photos/220453/pexels-photo-220453.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    firstName: "Shahadat",
    lastName: "Hossain Shuvo",
    email: "shahadat@baiust.edu.bd",
    phone: "01954677860",
    facebook: "/shahadat786",
    country: "BD",
    state: "Chittagong",
    city: "Cumilla",
    skills: ["html", "css", "js"],
    interests: ["footboll", "cricket"],
  },
  {
    id: 2,
    imgURL:
      "https://images.pexels.com/photos/937481/pexels-photo-937481.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    firstName: "Nuri",
    lastName: "Zerin",
    email: "zerin@baiust.edu.bd",
    phone: "01788996655",
    facebook: "/zerin_001",
    country: "BD",
    state: "Chittagong",
    city: "Cumilla",
    skills: ["c++", "python", "js"],
    interests: ["story-write", "cricket"],
  },
  {
    id: 3,
    imgURL:
      "https://images.pexels.com/photos/941693/pexels-photo-941693.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    firstName: "Abdul",
    lastName: "KArim",
    email: "karim@baiust.edu.bd",
    phone: "01787852655",
    facebook: "/karim_001",
    country: "BD",
    state: "Dhaka",
    city: "Dhaka",
    skills: ["c", "java", "js"],
    interests: ["basketball", "football"],
  },
  {
    id: 4,
    imgURL:
      "https://images.pexels.com/photos/1681010/pexels-photo-1681010.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500",
    firstName: "asif",
    lastName: "akbar",
    email: "akbar@baiust.edu.bd",
    phone: "01787857855",
    facebook: "/asif_001",
    country: "BD",
    state: "Khulna",
    city: "Bagerhat",
    skills: ["html", "css", "js"],
    interests: ["video-game", "social-media"],
  },
  {
    id: 5,
    imgURL:
      "https://images.pexels.com/photos/874158/pexels-photo-874158.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940",
    firstName: "Kabir",
    lastName: "Shekh",
    email: "kabir@baiust.edu.bd",
    phone: "01968857855",
    facebook: "/kabir_001",
    country: "USA",
    state: "California",
    city: "Los Angels",
    skills: ["python", "React", "js"],
    interests: ["gardening", "traveling"],
  },
];

export default Data;
